services:
  mysql:
    image: mysql:8
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: freeradius
      MYSQL_USER: bouncer
      MYSQL_PASSWORD: bouncer